# Generated by Django 5.2.8 on 2026-02-09 15:07

import apps.sellers.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to=apps.sellers.storage.seller_profile_image_path)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.sellers.storage.seller_cover_image_path)),
                ('store_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
